<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AnggotaAsramaSeeder extends Seeder
{
    public function run()
    {
        DB::table('anggota_asramas')->insert([
            [
                'nama' => 'Ahmad Ridho',
                'nim' => '123456789001',
                'fakultas' => 'Teknik',
                'prodi' => 'Sistem Informasi',
                'jenis_kelamin' => 'Laki-laki',
                'foto' => 'foto_profil/putra.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bagas Pratama',
                'nim' => '123456789002',
                'fakultas' => 'Teknik',
                'prodi' => 'Informatika',
                'jenis_kelamin' => 'Laki-laki',
                'foto' => 'foto_profil/putra.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Fahmi Hidayat',
                'nim' => '123456789003',
                'fakultas' => 'Ekonomi',
                'prodi' => 'Akuntansi',
                'jenis_kelamin' => 'Laki-laki',
                'foto' => 'foto_profil/putra.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dimas Arya',
                'nim' => '123456789004',
                'fakultas' => 'Hukum',
                'prodi' => 'Ilmu Hukum',
                'jenis_kelamin' => 'Laki-laki',
                'foto' => 'foto_profil/putra.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rizky Ananda',
                'nim' => '123456789005',
                'fakultas' => 'Pertanian',
                'prodi' => 'Agroteknologi',
                'jenis_kelamin' => 'Laki-laki',
                'foto' => 'foto_profil/putra.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Arif Budiman',
                'nim' => '123456789006',
                'fakultas' => 'Kedokteran',
                'prodi' => 'Kedokteran Umum',
                'jenis_kelamin' => 'Laki-laki',
                'foto' => 'foto_profil/putra.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Ilham Saputra',
                'nim' => '123456789007',
                'fakultas' => 'MIPA',
                'prodi' => 'Matematika',
                'jenis_kelamin' => 'Laki-laki',
                'foto' => 'foto_profil/putra.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Yusuf Maulana',
                'nim' => '123456789008',
                'fakultas' => 'Teknik',
                'prodi' => 'Teknik Elektro',
                'jenis_kelamin' => 'Laki-laki',
                'foto' => 'foto_profil/putra.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Galih Prawira',
                'nim' => '123456789009',
                'fakultas' => 'Ilmu Sosial',
                'prodi' => 'Sosiologi',
                'jenis_kelamin' => 'Laki-laki',
                'foto' => 'foto_profil/putra.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Aditya Raka',
                'nim' => '123456789010',
                'fakultas' => 'Ilmu Komputer',
                'prodi' => 'Teknologi Informasi',
                'jenis_kelamin' => 'Laki-laki',
                'foto' => 'foto_profil/putra.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nama' => 'Putri Wulandari',
                'nim' => '123456789011',
                'fakultas' => 'Kesehatan',
                'prodi' => 'Keperawatan',
                'jenis_kelamin' => 'Perempuan',
                'foto' => 'foto_profil/putri.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Nadia Zahra',
                'nim' => '123456789012',
                'fakultas' => 'Ekonomi',
                'prodi' => 'Manajemen',
                'jenis_kelamin' => 'Perempuan',
                'foto' => 'foto_profil/putri.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Salsabila Aulia',
                'nim' => '123456789013',
                'fakultas' => 'Ilmu Komunikasi',
                'prodi' => 'Public Relations',
                'jenis_kelamin' => 'Perempuan',
                'foto' => 'foto_profil/putri.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Intan Permata',
                'nim' => '123456789014',
                'fakultas' => 'Psikologi',
                'prodi' => 'Psikologi',
                'jenis_kelamin' => 'Perempuan',
                'foto' => 'foto_profil/putri.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rina Kartika',
                'nim' => '123456789015',
                'fakultas' => 'Ilmu Sosial',
                'prodi' => 'Antropologi',
                'jenis_kelamin' => 'Perempuan',
                'foto' => 'foto_profil/putri.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Ayu Lestari',
                'nim' => '123456789016',
                'fakultas' => 'MIPA',
                'prodi' => 'Biologi',
                'jenis_kelamin' => 'Perempuan',
                'foto' => 'foto_profil/putri.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Mega Putri',
                'nim' => '123456789017',
                'fakultas' => 'Teknik',
                'prodi' => 'Teknik Sipil',
                'jenis_kelamin' => 'Perempuan',
                'foto' => 'foto_profil/putri.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Fira Anjani',
                'nim' => '123456789018',
                'fakultas' => 'Ilmu Budaya',
                'prodi' => 'Sastra Indonesia',
                'jenis_kelamin' => 'Perempuan',
                'foto' => 'foto_profil/putri.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Tiara Melani',
                'nim' => '123456789019',
                'fakultas' => 'Ilmu Komputer',
                'prodi' => 'Sistem Informasi',
                'jenis_kelamin' => 'Perempuan',
                'foto' => 'foto_profil/putri.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Citra Rahma',
                'nim' => '123456789020',
                'fakultas' => 'Pertanian',
                'prodi' => 'Ilmu Tanah',
                'jenis_kelamin' => 'Perempuan',
                'foto' => 'foto_profil/putri.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
