<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AnggotaAsramaSeeder extends Seeder
{
    public function run()
    {
        DB::table('anggota_asramas')->insert([
            [
                'nama' => 'Ahmad Ridho',
                'nim' => '123456789001',
                'fakultas' => 'FRI',
                'prodi' => 'Sistem Informasi',
                'jenis_kelamin' => 'Laki-laki',
                'foto' => 'foto_profil/putra.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bagas Pratama',
                'nim' => '123456789002',
                'fakultas' => 'FIF',
                'prodi' => 'Informatika',
                'jenis_kelamin' => 'Laki-laki',
                'foto' => 'foto_profil/putra.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Fahmi Hidayat',
                'nim' => '123456789003',
                'fakultas' => 'FKS',
                'prodi' => 'Akuntansi',
                'jenis_kelamin' => 'Laki-laki',
                'foto' => 'foto_profil/putra.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dimas Arya',
                'nim' => '123456789004',
                'fakultas' => 'FEB',
                'prodi' => 'MBTI',
                'jenis_kelamin' => 'Laki-laki',
                'foto' => 'foto_profil/putra.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rizky Ananda',
                'nim' => '123456789005',
                'fakultas' => 'FIT',
                'prodi' => 'SIA',
                'jenis_kelamin' => 'Laki-laki',
                'foto' => 'foto_profil/putra.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Arif Budiman',
                'nim' => '123456789006',
                'fakultas' => 'FTE',
                'prodi' => 'Teknik Elektro',
                'jenis_kelamin' => 'Laki-laki',
                'foto' => 'foto_profil/putra.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Ilham Saputra',
                'nim' => '123456789007',
                'fakultas' => 'FIK',
                'prodi' => 'DKV',
                'jenis_kelamin' => 'Laki-laki',
                'foto' => 'foto_profil/putra.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Yusuf Maulana',
                'nim' => '123456789008',
                'fakultas' => 'FTE',
                'prodi' => 'Teknik Elektro',
                'jenis_kelamin' => 'Laki-laki',
                'foto' => 'foto_profil/putra.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Galih Prawira',
                'nim' => '123456789009',
                'fakultas' => 'FKS',
                'prodi' => 'Administrasi Bisnis',
                'jenis_kelamin' => 'Laki-laki',
                'foto' => 'foto_profil/putra.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Aditya Raka',
                'nim' => '123456789010',
                'fakultas' => 'FIF',
                'prodi' => 'Teknologi Informasi',
                'jenis_kelamin' => 'Laki-laki',
                'foto' => 'foto_profil/putra.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nama' => 'Putri Wulandari',
                'nim' => '123456789011',
                'fakultas' => 'FTE',
                'prodi' => 'Teknik Biomedis',
                'jenis_kelamin' => 'Perempuan',
                'foto' => 'foto_profil/putri.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Nadia Zahra',
                'nim' => '123456789012',
                'fakultas' => 'FRI',
                'prodi' => 'Teknik Industri',
                'jenis_kelamin' => 'Perempuan',
                'foto' => 'foto_profil/putri.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Salsabila Aulia',
                'nim' => '123456789013',
                'fakultas' => 'FKS',
                'prodi' => 'Public Relations',
                'jenis_kelamin' => 'Perempuan',
                'foto' => 'foto_profil/putri.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Intan Permata',
                'nim' => '123456789014',
                'fakultas' => 'FKS',
                'prodi' => 'Psikologi',
                'jenis_kelamin' => 'Perempuan',
                'foto' => 'foto_profil/putri.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rina Kartika',
                'nim' => '123456789015',
                'fakultas' => 'FIK',
                'prodi' => 'Desain Produk',
                'jenis_kelamin' => 'Perempuan',
                'foto' => 'foto_profil/putri.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Ayu Lestari',
                'nim' => '123456789016',
                'fakultas' => 'FTE',
                'prodi' => 'Teknik Telekomunikasi',
                'jenis_kelamin' => 'Perempuan',
                'foto' => 'foto_profil/putri.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Mega Putri',
                'nim' => '123456789017',
                'fakultas' => 'FRI',
                'prodi' => 'Teknik Logistik',
                'jenis_kelamin' => 'Perempuan',
                'foto' => 'foto_profil/putri.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Fira Anjani',
                'nim' => '123456789018',
                'fakultas' => 'FIF',
                'prodi' => 'Teknik Komputer',
                'jenis_kelamin' => 'Perempuan',
                'foto' => 'foto_profil/putri.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Tiara Melani',
                'nim' => '123456789019',
                'fakultas' => 'FRI',
                'prodi' => 'Sistem Informasi',
                'jenis_kelamin' => 'Perempuan',
                'foto' => 'foto_profil/putri.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Citra Rahma',
                'nim' => '123456789020',
                'fakultas' => 'FKS',
                'prodi' => 'Ilmu Komunikasi',
                'jenis_kelamin' => 'Perempuan',
                'foto' => 'foto_profil/putri.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
